# Generated by Django 3.1.7 on 2021-04-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='EarPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('inStockQty', models.IntegerField()),
                ('FreeGift', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Ear Phone',
                'verbose_name_plural': 'Ear Phones',
            },
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('inStockQty', models.IntegerField()),
                ('FreeGift', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Mobile Phone',
                'verbose_name_plural': 'Mobile Phones',
            },
        ),
        migrations.CreateModel(
            name='SaveBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('FreeGift', models.CharField(max_length=40)),
            ],
        ),
    ]
