# Generated by Django 3.1.7 on 2021-04-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savebill',
            name='applied_discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
