# Generated by Django 3.1.7 on 2021-04-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileStore', '0002_savebill_applied_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='discount',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='savebill',
            name='applied_discount',
            field=models.IntegerField(default=0),
        ),
    ]
