# Generated by Django 3.1.7 on 2021-04-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileStore', '0003_auto_20210422_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='savebill',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
            preserve_default=False,
        ),
    ]
